import {
  AcademicCapIcon,
  ArrowUpIcon,
  BriefcaseIcon,
  CameraIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CogIcon,
  GlobeAltIcon,
  HomeIcon,
  IdentificationIcon,
  InformationCircleIcon,
  KeyIcon,
  LinkIcon,
  LockClosedIcon as LockClosedOutlineIcon,
  MicrophoneIcon,
  PencilIcon,
  PlusIcon,
  StarIcon,
  TrashIcon,
  UserGroupIcon,
  VideoCameraIcon,
  UserIcon,
  UserCircleIcon,
  Bars3Icon,
} from '@heroicons/react/24/outline';
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  EyeIcon,
  LockClosedIcon,
  PlayIcon,
  XCircleIcon,
} from '@heroicons/react/24/solid';

export const iconMap = {
  'academic-cap': AcademicCapIcon,
  action: ChevronRightIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-up': ArrowUpIcon,
  back: ArrowLeftIcon,
  briefcase: BriefcaseIcon,
  camera: CameraIcon,
  check: CheckIcon,
  'check-filled': CheckCircleIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-right': ChevronRightIcon,
  close: XCircleIcon,
  cog: CogIcon,
  dismiss: XCircleIcon,
  error: ExclamationCircleIcon,
  'exclamation-circle': ExclamationCircleIcon,
  external: ArrowRightIcon,
  globe: GlobeAltIcon,
  home: HomeIcon,
  'id-card': IdentificationIcon,
  info: InformationCircleIcon,
  jump: ChevronDownIcon,
  key: KeyIcon,
  left: ArrowLeftIcon,
  link: LinkIcon,
  lock: LockClosedIcon,
  'lock-outline': LockClosedOutlineIcon,
  menu: Bars3Icon,
  more: ArrowRightIcon,
  pencil: PencilIcon,
  play: PlayIcon,
  plus: PlusIcon,
  podcast: MicrophoneIcon,
  right: ArrowRightIcon,
  star: StarIcon,
  trash: TrashIcon,
  up: ArrowUpIcon,
  user: UserIcon,
  'user-circle': UserCircleIcon,
  'user-group': UserGroupIcon,
  video: VideoCameraIcon,
  visible: EyeIcon,
  'x-circle': XCircleIcon,
};

// Base size and position of each icon (finetuned manually)
// Only add to this map if different from default class w-1em
export const iconBaseStyle = {
  default: 'w-1em',
  'academic-cap': 'w-08em -mt-02em',
  'arrow-left': 'w-08em -mt-02em',
  'arrow-right': 'w-08em -mt-02em',
  camera: 'w-1em -mt-02em',
  download: 'w-08em -mt-02em',
  back: 'w-1em -mt-02em',
  'chevron-right': 'w-1em -mt-02em',
  'chevron-down': 'w-1em -mt-01em',
  email: 'w-[1.2em]',
  external: 'w-08em -rotate-45 group-hover:-rotate-45 group-focus:-rotate-45',
  home: '-mt-02em',
  left: 'w-08em -mt-02em',
  link: '-mt-01em',
  lock: 'w-08em -mt-02em',
  'lock-outline': 'w-08em -mt-02em',
  more: 'w-08em -mt-02em',
  plus: 'w-08em -mt-02em',
  pencil: 'w-1em -mt-02em',
  right: 'w-08em -mt-02em',
  star: 'w-08em -mt-02em',
  trash: 'w-1em -mt-02em',
  up: 'w-1em -mt-03em',
  upload: 'w-08em -mt-02em',
  user: 'w-08em -mt-02em',
  'user-circle': 'w-[1.2em] -mt-02em',
};
