backend:
  name: git-gateway
  branch: nextjs
media_folder: "public/img"
public_folder: "/img"
# This creates PRs for every change. Only enable after go-live.
# publish_mode: editorial_workflow
site_url: https://elegant-poitras-87214a.netlify.com
collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - file: content/_settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - label: Children
                name: children
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string}
                  - label: Children
                    name: children
                    widget: list
                    fields:
                      - {label: Label, name: label, widget: string}
                      - {label: Path, name: path, widget: string}
  - label: "Homepage"
    name: "homepage"
    files:
      - label: "Welcome To Decanter"
        name: "homepage"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    delete: true
    description: "Basic building block pages. You may use markdown or html."
    folder: "content/_pages"
    preview_path: page/{{slug}}
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "components"
    label: "Components"
    description: "Component pages."
    folder: "content/_components"
    preview_path: component/{{slug}}
    create: true
    summary: "{{title}} Group: {{group}} Modifiers: {{modifier_css}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Unique ID", name: "uid", widget: "string" }
      - label: "Component Group"
        name: "group"
        widget: "select"
        options: ["basic", "advanced", "identity"]
      - { label: "Experimental", name: "experimental", widget: "boolean", default: false }
      - { label: "Deprecated", name: "deprecated", widget: "boolean", default: false }
      - { label: "Browser compatibility", name: "browsers", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - label: Modifier Classes
        name: modifier_css
        widget: list
        fields:
          - { label: "Human Readable Name", name: label, widget: string }
          - { label: "CSS Class", name: css_class, widget: string, hint: "No preceeding period. eg: su-card" }
          - { label: "Experimental", name: "experimental", widget: "boolean", default: false }
          - { label: "Deprecated", name: "deprecated", widget: "boolean", default: false }
      - { label: "SCSS Path", name: "scss_path", widget: "string", hint: "Relative to the Decanter project root." }
      - { label: "Template Path", name: "template_path", widget: "string", hint: "Relative to the Decanter project root." }
      - { label: "Template Markup", name: "template_markup", widget: "text", hint: "This overrides the template path." }
      - { label: "Source Data", name: "source_json", widget: "text", hint: "JSON data to populate the template with. Leave empty to use what is in the Decanter repo." }
      - { label: "Notes", name: "notes", widget: "markdown" }
