backend:
  name: git-gateway
  branch: nextjs
media_folder: "public/img"
public_folder: "/img"
# This creates PRs for every change. Only enable after go-live.
# publish_mode: editorial_workflow
site_url: https://elegant-poitras-87214a.netlify.com
collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - file: content/_settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - label: Children
                name: children
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string}
                  - label: Children
                    name: children
                    widget: list
                    fields:
                      - {label: Label, name: label, widget: string}
                      - {label: Path, name: path, widget: string}
  - label: "Homepage"
    name: "homepage"
    files:
      - label: "Welcome To Decanter"
        name: "homepage"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    delete: true
    description: "Basic building block pages. You may use markdown or html."
    folder: "content/_pages"
    preview_path: page/{{slug}}
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "components"
    label: "Components"
    description: "Component pages."
    folder: "content/_components"
    create: true
    identifier_field: component
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Top Content", name: "body", widget: "markdown" }
      - { label: "Component URL Key", name: "component", widget: "string", hint: "eg: composite-card from /components/composite-card" }
      - { label: "Bottom Content", name: "bottomcontent", widget: "markdown" }
      - { label: "Browser compatibility", name: "browsers", widget: "string" }
      - { label: "Top Content", name: "topcontent", widget: "markdown" }
      - { label: "Background Color (eg: /#FF00FF)", name: "bgcolor", widget: "string" }
      - { label: "Example width (%|px)", name: "egwidth", widget: "string" }
      - label: Modifier Classes
        name: modifier_css
        widget: list
        fields:
          - { label: "Variant CSS Class", name: css_class, widget: string, hint: "No preceeding period. eg: su-card" }
          - { label: "Source Data", name: "source_json", widget: "text", hint: "JSON data to populate the template with. Leave empty to use what is in the Decanter repo." }
          - { label: "Background Color (eg: /#FF00FF)", name: "bgcolor", widget: "string" }
          - { label: "Example width (%|px)", name: "egwidth", widget: "string", hint: "defaults to the global value if set." }
          - { label: "Description Override", name: "description", widget: "markdown", hint: "overrides the description from KSS" }
          - { label: "Notes", name: "notes", widget: "markdown", hint: "Shows up between the example and the markup code block." }
