import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="su-cc su-identity-bar su-pt-5 su-pb-3 su-bg-cardinal-red">
          <a className="su-logo su-text-white hocus:su-text-white su-text-20 su-leading-none" href="https://www.stanford.edu">
            Stanford University
          </a>
        </div>
        <h1 className="text-7xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  )
}

export default Home
