# Sass Renderer
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false
  includePaths:
    - node_modules
    - node_modules/bourbon/core
    - node_modules/decanter/core/src/scss

# Twig Renderer
twig:
  extensions:
    - twig-drupal-filters
  namespaces:
    hexo: themes/decanter2020/layout
    decanter: node_modules/decanter/core/src/templates
    node_modules: node_modules

# Assets
css: css
js: js
images: assets
