# Twig Renderer
twig:
  extensions:
    - twig-drupal-filters
  namespaces:
    hexo: themes/decanter2020/layout
    decanter: node_modules/decanter/core/src/templates
    node_modules: node_modules

# Assets
css: css
js: js
images: assets
