name: Run Eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install modules
        run: npm ci
        env:
          # The following var needs to correspond with what's used in the .npmrc file for fa pro
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FA_NPM_TOKEN }}
      - name: Run ESLint
        run: npm run lint
        env:
          # The following var needs to correspond with what's used in the .npmrc file for fa pro
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FA_NPM_TOKEN }}
