name: Merge to Stage

on:
  push:
    branches:
      - dev

jobs:
  merge-to-stage:
    name: Merge to Stage
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Merge dev into staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: staging
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
